name: flutter_login
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.0
  get_version: ^0.0.8+5
  flutter_whatsnew: ^0.2.0+3
  shared_preferences: ^0.5.6+1
  local_auth: ^0.6.1
  cupertino_icons: ^0.1.2
  persist_theme: ^1.6.0
  http: ^0.12.0+1
  json_annotation: ^2.0.0
  provider: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - CHANGELOG.md
